# Generated by Django 4.0.4 on 2022-04-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('highlighted_info', models.CharField(max_length=200)),
                ('youtube_link', models.URLField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
