# Generated by Django 4.0.4 on 2022-04-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_session', '0002_trainingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
