# Generated by Django 4.0.3 on 2022-03-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_coach',
        ),
    ]
